# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Название виджета')),
            ],
            options={
                'managed': False,
                'verbose_name': 'виджет',
                'verbose_name_plural': 'виджеты',
                'ordering': ['user', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Название задачи')),
            ],
            options={
                'verbose_name_plural': 'задачи',
                'managed': False,
                'verbose_name': 'задача',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(editable=False, max_length=255, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'muser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255, verbose_name='Правило')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'правила для виджетов',
                'verbose_name': 'правило для виджета',
            },
        ),
    ]
