# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Имя')),
                ('value', models.TextField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='ServerGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'группа серверов',
                'verbose_name_plural': 'группы серверов',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('config', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'сервер',
                'verbose_name_plural': 'серверы',
            },
        ),
        migrations.AddField(
            model_name='servergroups',
            name='servers',
            field=models.ManyToManyField(blank=True, to='heartbeat.Servers', verbose_name='Серверы'),
        ),
    ]
