# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0002_filldb'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='qosguialarm',
            field=models.BooleanField(default=False, verbose_name='Оповещать о событиях heartbeat в основном интерфейсе сервера'),
        ),
    ]
