# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0004_hosts_items_tasksets_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': 'блок контроля', 'verbose_name_plural': 'heartbeat - блоки контроля (hosts)'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'сборщик данных', 'verbose_name_plural': 'heartbeat - сборщики данных (items)'},
        ),
        migrations.AlterModelOptions(
            name='servergroups',
            options={'verbose_name': 'группа серверов', 'verbose_name_plural': 'qos - группы серверов'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name': 'сервер', 'verbose_name_plural': 'qos - серверы'},
        ),
        migrations.AlterModelOptions(
            name='tasksets',
            options={'verbose_name': 'задача сбора данных', 'verbose_name_plural': 'heartbeat - задачи сбора данных'},
        ),
        migrations.AlterModelOptions(
            name='triggers',
            options={'verbose_name': 'порог оповещения', 'verbose_name_plural': 'heartbeat - пороги оповещения (triggers)'},
        ),
        migrations.AddField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='tasksets',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
    ]
