# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0005_auto_20170731_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': 'узел сети', 'verbose_name_plural': 'heartbeat - узлы сети (hosts)'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'элемент данных', 'verbose_name_plural': 'heartbeat - элементы данных (items)'},
        ),
        migrations.AlterModelOptions(
            name='triggers',
            options={'verbose_name': 'триггер', 'verbose_name_plural': 'heartbeat - триггеры'},
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='agentkey',
        ),
        migrations.RemoveField(
            model_name='items',
            name='type',
        ),
        migrations.AddField(
            model_name='hosts',
            name='key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ узла'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя узла'),
        ),
        migrations.AddField(
            model_name='items',
            name='key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ опроса'),
        ),
        migrations.AddField(
            model_name='triggers',
            name='countoperator',
            field=models.CharField(default='', max_length=2, verbose_name='Кол-во результатов: условие'),
        ),
        migrations.AddField(
            model_name='triggers',
            name='countvalue',
            field=models.CharField(default='', max_length=255, verbose_name='Кол-во результатов: значение'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя опроса'),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(default='', max_length=255, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heartbeat.Items', verbose_name='Сборщик данных'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='operator',
            field=models.CharField(default='', max_length=2, verbose_name='Результат: условие'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='severity',
            field=models.CharField(default='', max_length=20, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Результат: значение'),
        ),
    ]
