# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0006_auto_20170911_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggers',
            name='item',
        ),
        migrations.AddField(
            model_name='tasksets',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='heartbeat.Triggers', verbose_name='Триггеры'),
        ),
        migrations.AddField(
            model_name='triggers',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя триггера'),
        ),
        migrations.AlterField(
            model_name='items',
            name='key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ параметра'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя параметра'),
        ),
        migrations.AlterField(
            model_name='tasksets',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='heartbeat.Hosts', verbose_name='Узлы сети'),
        ),
        migrations.AlterField(
            model_name='tasksets',
            name='items',
            field=models.ManyToManyField(blank=True, to='heartbeat.Items', verbose_name='Элементы данных'),
        ),
    ]
