# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0008_auto_20170912_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFormatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Имя обработчика')),
                ('config', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'обработка результата',
                'verbose_name_plural': 'heartbeat - обработка результата',
            },
        ),
        migrations.AlterField(
            model_name='hosts',
            name='config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ узла (routing key)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='items',
            name='key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ параметра (parameter key)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='items',
            name='resultformatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heartbeat.ResultFormatters', verbose_name='Обработчик результата'),
        ),
    ]
