# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0009_auto_20170914_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': 'узел сети', 'verbose_name_plural': 'hb -> задачи -> узлы сети (hosts)'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'элемент данных', 'verbose_name_plural': 'hb -> задачи -> элементы данных (items)'},
        ),
        migrations.AlterModelOptions(
            name='resultformatters',
            options={'verbose_name': 'обработкчик результата', 'verbose_name_plural': 'hb -> задачи -> элементы данных -> обработка результата'},
        ),
        migrations.AlterModelOptions(
            name='servergroups',
            options={'verbose_name': 'группа серверов', 'verbose_name_plural': 'qos -> группы серверов'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name': 'сервер', 'verbose_name_plural': 'qos -> серверы'},
        ),
        migrations.AlterModelOptions(
            name='tasksets',
            options={'verbose_name': 'задача сбора данных', 'verbose_name_plural': 'hb -> задачи сбора данных'},
        ),
        migrations.AlterModelOptions(
            name='triggers',
            options={'verbose_name': 'триггер', 'verbose_name_plural': 'hb -> задачи -> триггеры'},
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='countoperator',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='countvalue',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='triggers',
            name='value',
        ),
        migrations.AddField(
            model_name='triggers',
            name='config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='triggers',
            name='durability',
            field=models.IntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
    ]
