# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0010_auto_20170916_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='durability',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='severity',
            field=models.CharField(choices=[('high', 'Высокая'), ('low', 'Низкая')], default='high', max_length=255, verbose_name='Важность'),
        ),
    ]
