# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0011_auto_20170916_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': 'узел сети', 'verbose_name_plural': 'hb -> узлы сети (hosts)'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'элемент данных', 'verbose_name_plural': 'hb -> элементы данных (items)'},
        ),
        migrations.AlterModelOptions(
            name='resultformatters',
            options={'verbose_name': 'обработкчик результата', 'verbose_name_plural': 'hb -> обработка результата'},
        ),
        migrations.AlterModelOptions(
            name='triggers',
            options={'verbose_name': 'триггер', 'verbose_name_plural': 'hb -> триггеры'},
        ),
        migrations.RemoveField(
            model_name='tasksets',
            name='server',
        ),
        migrations.AddField(
            model_name='hosts',
            name='server',
            field=models.ForeignKey(default=12311122, on_delete=django.db.models.deletion.CASCADE, to='heartbeat.Servers', verbose_name='Сервер'),
            preserve_default=False,
        ),
    ]
