# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0012_auto_20170924_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='alarms',
            field=models.TextField(default='', verbose_name='Оповестить если'),
        ),
        migrations.AddField(
            model_name='items',
            name='alarms',
            field=models.TextField(default='', verbose_name='Оповестить если'),
        ),
        migrations.AlterField(
            model_name='servergroups',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя сервера'),
        ),
        migrations.AlterField(
            model_name='tasksets',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя задачи'),
        ),
    ]
