# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('heartbeat', '0013_auto_20171020_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='servergroups',
            name='usergroups',
            field=models.ManyToManyField(blank=True, help_text='Данная группа серверов будет видна только указанным группам пользователей.</br>Пользователям с правами "Администратор" и "Персонал" всегда будут видны все группы серверов.', to='auth.Group', verbose_name='Доступна для группы пользователей'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='alarms',
            field=models.TextField(blank=True, default='', help_text='Если одно из условий выполняется заданное время, пользователь получит оповещение.</br>Время может задаваться после условия. Если время не указано, оповещение срабатывает сразу</br>Время задается как количество периодов опроса (1p, 2p итд) по умолчанию один период равен 60 сек</br>Если настройки узла заданы, они заменяют одноименные настройки элемента данных на этом узле</br>Примеры (ключ параметра задается в настройках элемента данных):</br>cpuLoad >=20</br>temperature>10 1p</br>lan=2 3p</br>someParam</br>!someParam2 2p', verbose_name='Оповестить если'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='config',
            field=models.TextField(blank=True, default='', help_text='Настройки узла в формате JSON. Дополняют настройки элементов данных, работающих на этом узле</br>Например: {"item":"fanSpeed","resultcount":5} добавит опцию resultсоunt к элементу данных fanSpeed на этом узле'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='key',
            field=models.CharField(default='', help_text='Ключ маршрутизации RabbitMQ, который будет назначен всем сообщениям </br>на этом узле перед публикацией в RabbitMQ. Ключ маршрутизации может влиять на какую конкретно</br>машину с heartbeat agent будет отправлено задание от элемента данных.</br>Допускается создать несколько узлов с одинаковым ключом</br>Например, когда часть результатов от одного из heartbeat agent нужно вынести в отдельную плитку', max_length=255, verbose_name='Ключ узла (routing key)'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='name',
            field=models.CharField(default='', help_text='Название плитки heartbeat, понятное пользователю.</br>Допускается создавать узлы с одиннаковыми названиями,</br>при этом результаты по таким узлам будут выведены в общую плитку', max_length=255, verbose_name='Имя узла'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='server',
            field=models.ForeignKey(help_text='Сервер, к которому будет относиться плитка', on_delete=django.db.models.deletion.CASCADE, to='heartbeat.Servers', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='items',
            name='alarms',
            field=models.TextField(blank=True, default='', help_text='Если одно из условий выполняется заданное время, пользователь получит оповещение.</br>Время может задаваться после условия. Если время не указано, оповещение срабатывает сразу</br>Время задается как количество периодов опроса (1p, 2p итд) по умолчанию один период равен 60 сек</br>Если настройки узла заданы, они заменяют одноименные настройки элемента данных на этом узле</br>Примеры (ключ параметра задается в настройках элемента данных):</br>cpuLoad >=20</br>temperature>10 1p</br>lan=2 3p</br>someParam</br>!someParam2 2p', verbose_name='Оповестить если'),
        ),
        migrations.AlterField(
            model_name='items',
            name='config',
            field=models.TextField(default='', help_text='Настройки элемента данных в формате JSON. Определяют тип элемента данных и способ его работы</br>Например: {"item":"windowsFirewallStatus" }'),
        ),
        migrations.AlterField(
            model_name='items',
            name='key',
            field=models.CharField(default='', help_text='Код параметра. Используется при проверке условий.</br>Допускается создать несколько элементов данных с одинаковым ключом</br>Например, если параметр cpuLoad собирается разными способами на разных хостах', max_length=255, verbose_name='Ключ параметра (parameter key)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', help_text='Название параметра (метрики), понятное пользователю', max_length=255, verbose_name='Имя параметра'),
        ),
        migrations.AlterField(
            model_name='items',
            name='resultformatter',
            field=models.ForeignKey(blank=True, help_text='Дополнительные действия после получения значения от источника данных. Умножение, сложение, форматирование строки итд', null=True, on_delete=django.db.models.deletion.CASCADE, to='heartbeat.ResultFormatters', verbose_name='Обработчик результата'),
        ),
        migrations.AlterField(
            model_name='tasksets',
            name='name',
            field=models.CharField(help_text='Задачи сбора данных создают связи между хостами и элементами данных.</br>Имя задачи указывается для удобства настройки, оно не видно пользователю.</br>Допускается создание повторяющихся связей в разных задачах. Такие повторы будут автоматически устраняться.', max_length=255, verbose_name='Имя задачи'),
        ),
    ]
