# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0014_auto_20171026_1329'),
        ('heartbeat', '0014_auto_20171028_1731'),
    ]

    operations = [
    ]
