# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbupdate', '0002_filldb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridges',
            name='chcount',
            field=models.IntegerField(default=0, verbose_name='Количество каналов'),
        ),
    ]
